name: Merge sample metadata

on:
  push:
    branches:
      # When someone push to `main` branch
      - main
    paths:
      - 'samples/**/assets/sample.json'

jobs:
  build:
    name: 'Merge all sample.json files to samples.json'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Checkout Docs branch
        uses: actions/checkout@v2
        with:
          ref: Docs
          path: Docs
      - name: Join samples  
        run: |
          jq -s '[.[][]]' ./main/samples/**/assets/sample.json > ./main/.metadata/samples.json
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./main/templates/metadata-schema.json
          INPUT_JSONS: ./main/.metadata/samples.json
