name: Merge sample metadata

on:
  workflow_dispatch:
  push:
    branches:
      # When someone push to `main` branch
      - main
    paths:
      - 'samples/**/assets/sample.json'

jobs:
  build:
    name: 'Merge all sample.json files to samples.json'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: Join samples  
        run: |
          jq -s '[.[][]]' ./main/samples/**/assets/sample.json > ./main/.metadata/samples.json
          git add ./main/.metadata/samples.json
          git commit -m "Merged samples.json"
          git push origin main
