name: Merge sample metadata

on:
  workflow_dispatch:
  push:
    branches:
      # When someone push to `main` branch
      - main
    paths:
      - 'samples/**/assets/sample.json'

jobs:
  build:
    name: 'Merge all sample.json files to samples.json'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Join samples  
        run: |
          jq -s '[.[][]]' samples/**/assets/sample.json > .metadata/samples.json
      - mame: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merge all sample.json files to samples.json